# Site Settings
title: Yvonne Li
logo: "/assets/images/yli.png"
email: yvonneli.dev@gmail.com
description: >
  Hello Travellers!

# Author Settings
author:
  name: Yvonne Li
  email: yvonneli.dev@gmail.com

# Social Links
social:
  linkedin: https://www.linkedin.com/in/yvonneli-yli/
  github: https://github.com/yvonne-li

# SEO Settings
url: "https://yvonne-li.github.io" 
baseurl: "" 
lang: en_US
timezone: America/Toronto

markdown: kramdown
kramdown:
  input: GFM
# Exclude from processing
exclude:
  - vendor/
  - Gemfile.lock
  - node_modules/
  - README.md